clear;
clc;

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/ning1/Documents/FLOW
%    Lab/VAWTWakeModel/wake_model/data/velodatabase_SMG_surf4_matlab.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/05/12 08:56:42

%% Initialize variables.
filename = '/Users/ning1/Documents/MATLAB/EMG.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%	column13: double (%f)
%	column14: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TSR = dataArray{:, 1};
solidity = dataArray{:, 2};
% loc1 = dataArray{:, 3};
% loc2 = dataArray{:, 4};
% loc3 = dataArray{:, 5};
% spr1 = dataArray{:, 6};
% spr2 = dataArray{:, 7};
% spr3 = dataArray{:, 8};
% skw1 = dataArray{:, 9};
% skw2 = dataArray{:, 10};
% skw3 = dataArray{:, 11};
% scl1 = dataArray{:, 12};
% scl2 = dataArray{:, 13};
% scl3 = dataArray{:, 14};

loc1 = dataArray{:, 3};
loc2 = dataArray{:, 4};
loc3 = dataArray{:, 5};
spr1 = dataArray{:, 6};
spr2 = dataArray{:, 7};
skw1 = dataArray{:, 8};
skw2 = dataArray{:, 9};
scl1 = dataArray{:, 10};
scl2 = dataArray{:, 11};
scl3 = dataArray{:, 12};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
